version: '3.5'
services:
  redis-cache:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
     - client

  worker:
    container_name: workers
    depends_on:
      - redis-cache
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - './worker:/app'
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - client

networks:
  client:
    driver: 'bridge'