version: '3.5'
services:
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - './worker:/app'
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    networks:
      - worker

  redis-cache:
    image: redis
    ports:
      - '6379:6379'

networks:
  worker:
    driver: 'bridge'